#!/usr/bin/env bash
# Installs nginx on a server, listening via port 80.
# GET request to root returns a page that contains the string 'Hello World!'

# update the packages
apt-get update

# installs nginx
apt-get -y install nginx

# check if nginx installed
nginx -v || exit 1

# check firewall version
if ufw --version; then
	if ! ufw status; then
		ufw enable
	fi
	ufw allow 'Nginx HTTP'
	ufw allow ssh
fi

echo "Hello World!" > /var/www/html/index.html

# start nginx
service nginx start
