#!/usr/bin/env bash
# Installs nginx on a server, listening via port 80.
# GET request to root returns a page that contains the string 'Hello World!'

# update the packages
sudo apt-get update

# installs nginx
sudo apt-get -y install nginx

# check if nginx installed
nginx -v || exit 1

# check firewall version
if ufw -v; then
	if sudo service ufw status; then
		sudo ufw enable
	fi
	sudo ufw allow 'Nginx HTTP'
	sudo ufw allow ssh
fi

# start nginx
if sudo service nginx restart; then
	echo "Hello World!" > /var/www/html/index.html
fi
