#!/usr/bin/env bash
# Configures a Nginx server so that /redirect_me is redirecting to another page. 

# update the packages
apt-get update

# installs nginx
apt-get -y install nginx

# check if nginx installed
nginx -v || exit 1

# check firewall version
if ufw --version; then
	if ufw status | head -n 1 | grep -q "Status: inactive"; then
		ufw enable
	fi
	ufw allow 'Nginx HTTP'
	ufw allow ssh
fi

sed -i "/server_name _;/ a \ \n\trewrite /redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default

# start nginx
service nginx start
