#!/usr/bin/env bash
# Configures a Nginx server to have a custom 404 page that contains "Ceci n'est pas une page".

# update the packages
apt-get update

# installs nginx
apt-get -y install nginx

# check if nginx installed
nginx -v || exit 1

# check firewall version
if ufw --version; then
	if ufw status | head -n 1 | grep -q "Status: inactive"; then
		ufw enable
	fi
	ufw allow 'Nginx HTTP'
	ufw allow ssh
fi

sed -i "/server_name _;/ a \ \n\trewrite /redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /var/www/html/404.html
str="\ \n\t# custom error page configuration\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sed -i "/listen [::]:80 default_server;/ a $str" /etc/nginx/sites-available/default

# start nginx
service nginx start
