#!/usr/bin/env bash
# Configures Nginx so that its HTTP response contains a custom header "X-Served-By"

# update the packages
apt-get update

# installs nginx
apt-get -y install nginx

# check if nginx installed
nginx -v || exit 1

# check firewall version
if ufw --version; then
        if ufw status | head -n 1 | grep -q "Status: inactive"; then
                ufw enable
        fi
        ufw allow 'Nginx HTTP'
        ufw allow ssh
fi

sed -i "/server_name _;/ a \ \n\tadd_header X-Served-By \"$(hostname)\";" /etc/nginx/sites-available/default

# start nginx
service nginx restart
