#!/usr/bin/env bash
# Configures Nginx so that its HTTP response contains a custom header "X-Served-By"
sed -i "/server_name _;/ a \ \n\tadd_header X-served-by $(hostname);" /etc/nginx/sites-available/default
ervice nginx restart
