#!/usr/bin/env bash
# generates a MySQL dump and creates a compressed archive out of it

mysqldump -u root -p"$1" --all-databases > backup.sql
archive="$(date +%d-%m-%Y)"".tar.gz"
tar -czvf "$archive" backup.sql
