#!/usr/bin/env bash
# debugs a web stack so that curl 0:80 returns 200 code

if ! nginx -v; then
	sudo apt-get update
	sudo apt-get -y install nginx;
fi

if sudo ufw --version; then
	sudo ufw allow 'Nginx HTTP'
	sudo service ufw restart
fi

sudo service nginx restart
