#!/usr/bin/env bash
# A Bash script that displays a list of currently running processes.
# It must:
# 	Show all processes, for all users, including those which might not have a TTY
# 	Display in a user-oriented format
#	Show process hierarchy

ps -auxH
