#!/usr/bin/env bash
# A Bash script that:
# 	Creates the file /var/run/myscript.pid containing its PID
#	Displays To infinity and beyond indefinitely
#	Displays 'I hate the kill command' when receiving a SIGTERM signal
#	Displays 'Y U no love me?!' when receiving a SIGINT signal
#	Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

trap "echo 'I hate the kill command'; flag=1" TERM
trap "echo 'Y U no love me?!'; exit" INT
trap "flag=1" QUIT

flag=0
echo "$$" > /var/run/myscript.pid
while :
do
	if [ $flag -eq 1 ]
	then
		rm /var/run/myscript.pid
		exit
	fi

	echo "To infinity and beyond"
	sleep 2s
done
