#!/usr/bin/env bash
# A Bash script that displays the content of the file /etc/passwd.
# It only displays username, user id, Home directory path for the user
# in the format, <username>:<user id>:<home directory path>

file=/etc/passwd
IFS=':'

while read -r line ;
do
	read -r -a field <<< "$line";
	echo "${field[0]}:${field[2]}:${field[5]}" ;
done < $file
