#!/usr/bin/env bash
# A Bash script that displays content of the current directory
# in a list format where only the part of the name after the first dash is displayed

for file in * ;
do
	cut -d '-' -f 2 <<< "$file";
done
