#!/usr/bin/env bash
# A Bash script that gives you information about the school file.
# It prints the following, 
# 	if the file exists: school file exists
# 	if the file does not exist: school file does not exist
# It prints the following if the file exists, 
# 	 but is empty: school file is empty
# 	 but is not empty: school file is not empty
# if the file is a regular file: school is a regular file
# if the file is not a regular file: (nothing)

file="school"

if [ -a "$file" ] ;
then
	echo "school file exists";

	if [ -s "$file" ] ;
	then
		echo "school file is not empty";
	else
		echo "school file is empty";
	fi

	if [ -f "$file" ] ;
	then
		echo "school is a regular file";
	fi
else
	echo "school file does not exist";
fi
