#!/usr/bin/env bash
# Runs Nginx as the nginx user, listening on port 8080
sed -i 's/#user www-data/user nginx/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 004 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
